### ISSUE TITLE
Is there a way to change the Label Color?

### ISSUE THREAD

**Issue by evensolberg** [ibecav/CGPfunctions#14]
I can change the newggslopegraph data point color using `DataTextColor`, but there doesn't seem to be a corresponding way to change the label color. Am I missing something?

**Comment by ibecav** [comment]
Hi,

What do you mean by "label" in this case?  You can change the background color for the numeric labels with `DataLabelFillColor`

# not a great example but demonstrating functionality
newgdp$rGDP <- round(newgdp$GDP)

newggslopegraph(newgdp,
  Year,
  rGDP,
  Country,
  LineColor = c(rep("grey", 3), "red", rep("grey", 11)),
  DataTextSize = 3,
  DataLabelFillColor = "gray",
  DataLabelPadding = .2,
  DataLabelLineSize = .5
)

**Comment by ibecav** [comment]
No response from user
