### ISSUE TITLE
Save PlotXTabs output

### ISSUE THREAD

**Issue by gopi2904** [ibecav/CGPfunctions#15]
Is there a way to save PlotXTabs output in png or pdf?

**Comment by ibecav** [comment]
Yes you need to change your default graphics device.  That very much varies by systems and capabilities but here's how I'd do it quick and dirty on my mac inside the RStudio console window.  YMMV

`pdf(file = "myplot.pdf")`
`PlotXTabs(mtcars, am, vs)`
`dev.off()`
