### ISSUE TITLE
newggslopegraph: line color based on change over time/slope?

### ISSUE THREAD

**Issue by nkarimi** [ibecav/CGPfunctions#16]
Is there a way to color the lines (LineColor) based on the slope or change over time? For example, positive increase the line=green and for negative change the line=red? It would be the equivalent to your cancer dataset example where you used: LineColor = c("red", rep("gray",4), "red", rep("gray",3)). Thanks very much.

**Comment by ibecav** [comment]
Please see the last example in the vignette.  `LineColor` is just a character string you can either manually or via a script make it as simple or complex as you like.  I did add some additional example code to the vignette to demonstrate your use case.
