### ISSUE TITLE
The method to evaluate if dataframe exists only checks if it exists in Global Environment.

### ISSUE THREAD

**Issue by paul-chrlt** [ibecav/CGPfunctions#17]
**In `newggslopegraph.R` :**

If the dataframe is sent to `newggslopegraph()` in a local function, then the evaluation `Ndataframe <- deparse(substitute(dataframe))` doesn't return the name of the dataframe as intended, but the structure of the dataframe.

Then, when testing with `exists(Ndataframe)`, it always fails and returns FALSE, giving you the error "The first object in your list does not exist. It should be a dataframe"

A (dirty) workaround : creating a dataframe with the same name from the global environment.

**Comment by ibecav** [comment]
Thanks! I'll try and look at it when I get a chance.

**Comment by ibecav** [comment]
Should be fixed now
