### ISSUE TITLE
Chang linetype based on a grouping factor

### ISSUE THREAD

**Issue by nzechrist** [ibecav/CGPfunctions#30]
If I print the interaction plot in back and white, I am unable to differentiate the groups because the lines are solid for the entire group. That also applies for the points. I want to be able to vary the linetype to match one of the factors. For example, If I have a factor with two levels, I want to use solid line for level 1 and broken lines for level 2.

**Comment by ibecav** [comment]
For now I'm going to implement the simplest change which is to simply tie both the interaction linetype and the shape of the dots to the grouping variable.  `ggplot` will automatically cycle through the options for you.  When I have a chance I'll look at giving the user some choice.

**Comment by ibecav** [comment]
Same as last time I can't update CRAN version yet but you can get this version from github
