### ISSUE TITLE
formatting numbers in newggslopegraph

### ISSUE THREAD

**Issue by gilmeriken** [ibecav/CGPfunctions#37]
First, thanks for creating newggslope graph, it looks great.

How do I control the number format of the Measurement?
For example, what if I want the graph to display "X %", or if I want integers displayed with a thousands separator?

**Comment by ibecav** [comment]
Hi, looks like a good suggestion.  I'll try and add it this week.  I'll probably change things so that you can pass along a column name that contains labels formatted anyway you like.

**Comment by gilmeriken** [comment]
Thanks!

**Comment by ibecav** [comment]
Should be available in github via

# development version from GitHub
# install.packages("devtools")
devtools::install_github("ibecav/CGPfunctions", 
                         build_vignettes = TRUE,
                         upgrade = "ask")

**Comment by ibecav** [comment]
Some examples of how to use it...
```r
newcancer$datalabel <- paste0(newcancer$Survival, "%")
newggslopegraph(newcancer, Year, Survival, Type, Data.label = datalabel)
newcancer <- 
   newcancer %>% 
   mutate(datalabel = case_when(Type == "Thyroid" ~ "Humma", 
                                TRUE ~ NA_character_))
newggslopegraph(newcancer, Year, Survival, Type, Data.label = datalabel)

```
