### ISSUE TITLE
R package CGP functions library  load error

### ISSUE THREAD

**Issue by Nxatha** [ibecav/CGPfunctions#48]
> library(CGPfunctions)
Error: package or namespace load failed for ‘CGPfunctions’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘MatrixModels’

Need this package to access a few functions. What is the solution to this

**Comment by hank00000** [comment]
Same question, but for me the package that can't be found is 'Desctools', which isn't able to be downloaded at all from CRAN via R Studio either. So I suspect the CGPfunctions package is trying to draw off deprecated or gone dependencies?

**Comment by ibecav** [comment]
Sorry I can't replicate either of these and when I check CRAN via RStudio I find both these packages just fine.  Please check your own settings and you can confirm they exist at [CRAN](https://cran.r-project.org/web/packages/MatrixModels/index.html) and [CRAN](https://cran.r-project.org/web/packages/DescTools/).  You may be getting that error message for the simple reason you haven't installed on your local machine.

![Screenshot 2023-09-23 at 11 24 59 AM](https://github.com/ibecav/CGPfunctions/assets/26557145/314e7f5c-347e-4b49-97f6-a63d5884ee52)
![Screenshot 2023-09-23 at 11 23 47 AM](https://github.com/ibecav/CGPfunctions/assets/26557145/f7ec6581-129a-4063-b5f4-f4447c8d1021)

**Comment by Nxatha** [comment]
I resolved the issue a long time ago by just upgrading my version of R studio.
