### ISSUE TITLE
The function Plot2WayANOVA doesn't accept the palette and package options

### ISSUE THREAD

**Issue by chabrault** [ibecav/CGPfunctions#49]
Thank you for this nice package.
The parameters `package` and `palette` are not working in `Plot2WayANOVA` function. I checked the code and these are never called in the function. I think a small update could fix that.

**Comment by ibecav** [comment]
Yes I think I disconnected them when I added the `ggplot.component` capability awhile back.  It will do colors and palettes and just about anything else you want.  Try something like:

```
Plot2WayANOVA(mpg ~ am * vs, 
              mtcars, 
              confidence = .99, 
              ggplot.component = list(scale_color_brewer(palette="Accent"), 
              scale_fill_brewer(palette="Accent")))
```

**Comment by ibecav** [comment]
Or you could choose manual or pick another scale like something from Wes Anderson.  When I get a minute I'll update the doco...

```
Plot2WayANOVA(mpg ~ am * vs, 
              mtcars, 
              confidence = .99, 
              ggplot.component = list(scale_color_manual(values = wesanderson::wes_palette(n=3, name="GrandBudapest1")), 
                                      scale_fill_manual(values = wesanderson::wes_palette(n=3, name="GrandBudapest1"))))
```
