### ISSUE TITLE
PlotXTAbs2 is great + a very quick Question...switched plot legend labels?

### ISSUE THREAD

**Issue by sfd99** [ibecav/CGPfunctions#50]
**_Hi Chuck!_**

Thanks++ for the PlotXTabs2 pkg!.

**Q:**
in page:
https://cran.r-project.org/web/packages/CGPfunctions/vignettes/Using-PlotXTabs2.html

in the 2nd barplot from page top,
are the AM Legend labels
switched around?.

I may be wrong,
but for the **AM** column in mtcars,
isn't:
   AM = 0 ( zero ) ==> "Automatic " in red
and:  
   AM = 1 ( one ) ==> "Manual " in blue ?...

The image Legend
currently shows the opposite text labels...

Hey! please do correct me if I am wrong :-)
sfd99
SF

**Comment by ibecav** [comment]
You're 100% correct typo on my part ...
`[, 9]	am	Transmission (0 = automatic, 1 = manual)`
straight from the doco...

**Comment by sfd99** [comment]
Thanks Chuck,
for the very clear tutorials 
and great pkgs.
**sfd99
SF**
